"""gp3sequencespy: transparent ordered categorical sequence analysis."""

from ._exceptions import GP3SequencesError, ModelFitError, ParityError, ValidationError
from .adapters import (
    ArulesSequenceAdapter,
    GrpStringInput,
    WideSequenceAdapter,
    as_arules_sequences,
    as_grpstring_data,
    as_igraph_transition_network,
    as_seqhmm_sequences,
    as_traminer_sequences,
    prepare_gp3tools_sequences,
)
from .analysis_audit import (
    SequenceAnalysisAudit,
    SequenceAnalysisComparison,
    audit_sequence_analysis,
    compare_sequence_analysis_results,
)
from .capabilities import sequence_capabilities
from .consensus import (
    compare_sequence_groups,
    create_consensus_sequence,
    format_consensus_sequence,
    summarise_consensus_agreement,
)
from .covariate_hmm import (
    CovariateSequenceHMM,
    decode_covariate_sequence_states,
    fit_covariate_sequence_hmm,
    predict_covariate_transition_probabilities,
    summarise_covariate_sequence_hmm,
)
from .data import audit_sequence_data, prepare_sequence_data, validate_sequence_data
from .distances import (
    bootstrap_sequence_clusters,
    cluster_sequences,
    compute_sequence_distance,
    create_sequence_cluster_ensemble,
    extract_representative_sequences,
    summarise_sequence_cluster_stability,
    summarise_sequence_distance,
    validate_sequence_clusters,
)
from .hmm import (
    compare_sequence_hmms,
    decode_sequence_states,
    fit_sequence_hmm,
    fit_sequence_hmm_mixture,
    summarise_sequence_hmm,
)
from .inference import (
    bootstrap_sequence_group_difference,
    declare_sequence_comparison_design,
    plot_sequence_group_inference,
    summarise_sequence_group_inference,
    test_sequence_group_difference,
)
from .motif_visualisation import (
    MotifPositionResult,
    format_sequence_motif_positions,
    plot_sequence_motif_positions,
    plot_sequence_motifs,
    summarise_sequence_motif_positions,
)
from .motifs import (
    extract_sequence_ngrams,
    filter_sequence_motifs,
    format_sequence_motifs,
    summarise_sequence_motifs,
)
from .multichannel_hmm import (
    decode_multichannel_sequence_states,
    fit_multichannel_sequence_hmm,
    plot_multichannel_sequence_hmm,
    summarise_multichannel_sequence_hmm,
)
from .networks import (
    bootstrap_transition_network,
    create_transition_network,
    detect_transition_communities,
    fit_higher_order_transition_model,
    predict_next_state,
    summarise_transition_centrality,
)
from .panel import (
    compare_sequence_panel_changes,
    plot_sequence_panel_changes,
    prepare_sequence_panel,
    summarise_sequence_panel,
)
from .subsequences import (
    compare_sequence_subsequences,
    extract_sequence_subsequences,
    filter_sequence_subsequences,
    plot_sequence_subsequences,
    summarise_sequence_subsequences,
)
from .summaries import (
    encode_sequence_data,
    format_sequence_paths,
    summarise_sequence_states,
    summarise_sequence_transitions,
)
from .time_models import (
    TimeVaryingSequenceModel,
    fit_time_varying_sequence_model,
    plot_time_varying_sequence_model,
    predict_time_varying_sequence_model,
    summarise_time_varying_sequence_model,
)
from .visualisations import (
    plot_consensus_sequence,
    plot_sequence_cluster_silhouette,
    plot_sequence_distance_heatmap,
    plot_sequence_entropy,
    plot_sequence_group_comparison,
    plot_sequence_index,
    plot_sequence_state_distribution,
    plot_transition_network,
)

__version__ = "0.1.0"

__all__ = [
    "GP3SequencesError",
    "ValidationError",
    "ModelFitError",
    "ParityError",
    "CovariateSequenceHMM",
    "TimeVaryingSequenceModel",
    "MotifPositionResult",
    "WideSequenceAdapter",
    "ArulesSequenceAdapter",
    "GrpStringInput",
    "SequenceAnalysisAudit",
    "SequenceAnalysisComparison",
    "as_traminer_sequences",
    "as_arules_sequences",
    "as_grpstring_data",
    "as_seqhmm_sequences",
    "as_igraph_transition_network",
    "prepare_gp3tools_sequences",
    "sequence_capabilities",
    "audit_sequence_analysis",
    "compare_sequence_analysis_results",
    "plot_consensus_sequence",
    "plot_sequence_group_comparison",
    "plot_sequence_index",
    "plot_sequence_state_distribution",
    "plot_sequence_entropy",
    "plot_sequence_distance_heatmap",
    "plot_transition_network",
    "plot_sequence_cluster_silhouette",
    "audit_sequence_data",
    "validate_sequence_data",
    "prepare_sequence_data",
    "encode_sequence_data",
    "summarise_sequence_states",
    "summarise_sequence_transitions",
    "format_sequence_paths",
    "extract_sequence_ngrams",
    "summarise_sequence_motifs",
    "filter_sequence_motifs",
    "format_sequence_motifs",
    "summarise_sequence_motif_positions",
    "format_sequence_motif_positions",
    "plot_sequence_motifs",
    "plot_sequence_motif_positions",
    "create_consensus_sequence",
    "summarise_consensus_agreement",
    "format_consensus_sequence",
    "compare_sequence_groups",
    "compute_sequence_distance",
    "summarise_sequence_distance",
    "cluster_sequences",
    "validate_sequence_clusters",
    "extract_representative_sequences",
    "bootstrap_sequence_clusters",
    "summarise_sequence_cluster_stability",
    "create_sequence_cluster_ensemble",
    "create_transition_network",
    "summarise_transition_centrality",
    "detect_transition_communities",
    "fit_higher_order_transition_model",
    "predict_next_state",
    "bootstrap_transition_network",
    "prepare_sequence_panel",
    "summarise_sequence_panel",
    "compare_sequence_panel_changes",
    "plot_sequence_panel_changes",
    "extract_sequence_subsequences",
    "summarise_sequence_subsequences",
    "filter_sequence_subsequences",
    "compare_sequence_subsequences",
    "plot_sequence_subsequences",
    "fit_sequence_hmm",
    "fit_sequence_hmm_mixture",
    "decode_sequence_states",
    "summarise_sequence_hmm",
    "compare_sequence_hmms",
    "declare_sequence_comparison_design",
    "test_sequence_group_difference",
    "bootstrap_sequence_group_difference",
    "summarise_sequence_group_inference",
    "plot_sequence_group_inference",
    "fit_multichannel_sequence_hmm",
    "decode_multichannel_sequence_states",
    "summarise_multichannel_sequence_hmm",
    "plot_multichannel_sequence_hmm",
    "fit_covariate_sequence_hmm",
    "predict_covariate_transition_probabilities",
    "decode_covariate_sequence_states",
    "summarise_covariate_sequence_hmm",
    "fit_time_varying_sequence_model",
    "predict_time_varying_sequence_model",
    "summarise_time_varying_sequence_model",
    "plot_time_varying_sequence_model",
]
